### ISSUE TITLE
how to deploy a contract in cairo?

### ISSUE THREAD

**Issue by PerryNusbaum** [blockchain-audit/meridian-starknet#178]

**Comment by henry-hz** [comment]
Yes, providing clear steps on how to reproduce the bug is essential when asking a question about a bug on Stack Overflow. Here are some tips to help you formulate an effective question:

1. **Title**: Write a clear and concise title that summarizes the problem.
   - Example: "NullPointerException when trying to access an element in an ArrayList"

2. **Describe the Problem**: Explain what you are trying to do, what you expected to happen, and what actually happened.
   - Example: "I'm trying to iterate through an ArrayList and print each element, but I'm encountering a NullPointerException."

3. **Provide the Code**: Include the relevant code that causes the issue. Make sure to format it properly using the code formatting tools provided by Stack Overflow.
   - Example:
     ```java
     public class Main {
         public static void main(String[] args) {
             ArrayList<String> list = new ArrayList<>();
             list.add("One");
             list.add(null);
             list.add("Three");

             for (String item : list) {
                 System.out.println(item.length());
             }
         }
     }
     ```

4. **Steps to Reproduce**: Clearly outline the steps someone else needs to follow to reproduce the issue. This includes any setup steps, specific configurations, or other relevant details.
   - Example:
     1. Create a new Java project.
     2. Copy the provided code into the main class.
     3. Run the program.

5. **Error Messages**: Include any error messages or stack traces you are encountering. Format them properly for readability.
   - Example:
     ```
     Exception in thread "main" java.lang.NullPointerException
         at Main.main(Main.java:10)
     ```

6. **What You've Tried**: Mention any solutions or debugging steps you have already attempted. This helps others understand what you have already considered and prevents duplicate suggestions.
   - Example: "I tried checking if the item is null before calling `item.length()`, but I'm not sure if this is the best approach."

7. **Tags**: Use appropriate tags to categorize your question. This helps in getting attention from the right experts.
   - Example: `java`, `arraylist`, `nullpointerexception`

Putting it all together, here is an example of a well-structured question:

---

**Title**: NullPointerException when trying to access an element in an ArrayList

**Body**:

I'm trying to iterate through an ArrayList and print each element, but I'm encountering a NullPointerException.

Here is the code I'm using:

```java
public class Main {
    public static void main(String[] args) {
        ArrayList<String> list = new ArrayList<>();
        list.add("One");
        list.add(null);
        list.add("Three");

        for (String item : list) {
            System.out.println(item.length());
        }
    }
}
```

**Steps to Reproduce**:
1. Create a new Java project.
2. Copy the provided code into the main class.
3. Run the program.

**Error Message**:
```
Exception in thread "main" java.lang.NullPointerException
    at Main.main(Main.java:10)
```

I tried checking if the item is null before calling `item.length()`, but I'm not sure if this is the best approach. How can I handle this exception properly?

**Tags**: `java`, `arraylist`, `nullpointerexception`

---

By following these guidelines, you'll be able to ask a clear, concise, and well-structured question on Stack Overflow, increasing the chances of getting a helpful response.
